version: "3.9"
services:
  mysql:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
#  app:
#    build: ./src/Watchers.WebApi
#    ports:
#      - 5001:80